# netlify.toml
[build]
  command  = "npm ci && npm run build"
  publish  = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Make sure /admin routes to the static admin shell
[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200

# SPA/astro client-side routing fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200