# netlify.toml
[build]
  command  = "npm ci && npm run build"
  publish  = "dist"
  # If you use Netlify Functions, keep this:
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# SPA/astro client-side routing fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200