[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# OAuth endpoints expected by the GitHub backend
[[redirects]]
  from = "/oauth/*"
  to = "/.netlify/functions/oauth"
  status = 200

# CMS SPA routing (optional)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200