backend:
  name: github
  repo: judaicadh/earlymodernworkshop
  branch: main
  base_url: https://earlymodernworkshop.judaicadhpenn.org  # where the OAuth proxy lives

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/documents"    # change to your path(s)
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug",  name: "slug",  widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }