backend:
  name: github
  repo: judaicadh/earlymodernworkshop
  branch: main

  # IMPORTANT: point to your own site (the integration exposes /oauth here)
  base_url: https://earlymodernworkshop.judaicadhpenn.org
  auth_endpoint: oauth

media_folder: "src/assets"
public_folder: "/assets"

site_url: "https://earlymodernworkshop.judaicadhpenn.org"

collections:
  - name: "documents"
    label: "Documents"
    folder: "src/content/documents"
    create: true
    extension: "md"
    format: "frontmatter"

    slug: "{{slug}}"
    path: "{{fields.year}}/{{slug}}"      # write into documents/<year>/<slug>.md
    summary: "{{fields.year}} — {{title}}" # how each item appears in the list

    sortable_fields: ["commit_date", "year", "title"]
    view_groups:                           # optional: group the list by year
      - { label: "Year", field: "year" }

    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Year",  name: "year",  widget: "string", required: true }
      - { label: "Body",  name: "body",  widget: "markdown" }