backend:
  name: github
  repo: judaicadh/earlymodernworkshop
  branch: main

  # IMPORTANT: point to your own site (the integration exposes /oauth here)
  base_url: https://earlymodernworkshop.judaicadhpenn.org
  auth_endpoint: oauth

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://earlymodernworkshop.judaicadhpenn.org"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"   # change if needed
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug",  name: "slug",  widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }

  # Example: year-based docs (optional)
  - name: "documents"
    label: "Documents"
    folder: "src/content/documents"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year",  name: "year",  widget: "number" }
      - { label: "Body",  name: "body",  widget: "markdown" }