backend:
  name: github
  repo: judaicadh/earlymodernworkshop
  branch: main
  base_url: https://earlymodernworkshop.judaicadhpenn.org
  auth_endpoint: oauth

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://earlymodernworkshop.judaicadhpenn.org"

collections:
  - name: "documents"
    label: "Documents"
    folder: "src/content/documents"
    create: true
    extension: "md"
    format: "frontmatter"

    # Show folders by year: documents/<year>/<file>.md
    nested:
      depth: 2
      summary: "{{title}}"

    slug: "{{slug}}"
    path: "{{fields.year}}/{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Year",  name: "year",  widget: "number", required: true }
      - { label: "Body",  name: "body",  widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Slug",  name: "slug",  widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }