name: Deploy Astro site with TinaCMS to Pages

on:
  # Trigger workflow on push to the main branch
  push:
    branches: ["main"]

  # Allows you to manually trigger the workflow
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build TinaCMS
      - name: Build TinaCMS
        env:
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
        run: npx tinacms build
      
      # Step 5: Build the Astro site
      - name: Build Astro site
        run: npm run build

      # Step 6: Upload the artifact for GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Deploy the site to GitHub Pages
      - name: Deploy
        uses: actions/deploy-pages@v4
